// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAzL2ymoj7dIoPLJ3V-XmSjxgtCM75-90',
    appId: '1:918786192277:web:ce0bdd706b6c5d4acc7c9c',
    messagingSenderId: '918786192277',
    projectId: 'first-report-24222',
    authDomain: 'first-report-24222.firebaseapp.com',
    storageBucket: 'first-report-24222.firebasestorage.app',
    measurementId: 'G-9E71C1ZLN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8hNgAYO5N4PkYmSpjiRlffowJG4s8BYM',
    appId: '1:918786192277:android:a9fb0c7a2fb86e95cc7c9c',
    messagingSenderId: '918786192277',
    projectId: 'first-report-24222',
    storageBucket: 'first-report-24222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMQLGAoG8j6bAtP5m1BW6eCVvwWJcAdyo',
    appId: '1:918786192277:ios:3e98c985086e253acc7c9c',
    messagingSenderId: '918786192277',
    projectId: 'first-report-24222',
    storageBucket: 'first-report-24222.firebasestorage.app',
    iosBundleId: 'com.example.firstreport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMQLGAoG8j6bAtP5m1BW6eCVvwWJcAdyo',
    appId: '1:918786192277:ios:3e98c985086e253acc7c9c',
    messagingSenderId: '918786192277',
    projectId: 'first-report-24222',
    storageBucket: 'first-report-24222.firebasestorage.app',
    iosBundleId: 'com.example.firstreport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAzL2ymoj7dIoPLJ3V-XmSjxgtCM75-90',
    appId: '1:918786192277:web:6c5360f291c8c84acc7c9c',
    messagingSenderId: '918786192277',
    projectId: 'first-report-24222',
    authDomain: 'first-report-24222.firebaseapp.com',
    storageBucket: 'first-report-24222.firebasestorage.app',
    measurementId: 'G-1WHR0VL7SL',
  );

}